# This is a basic workflow to help you get started with the CI/CD for Functions Project
name: Build and Deploy Job

# Controls when the workflow will run
on:
  pull_request:
    branches: [develop]
    types: [closed]

env:
  # Description: Your function app name on Azure
  # TODO : Replace <function_app_name> with the name of your function app
  AZURE_FUNCTIONAPP_NAME: my-first-function-20231027191045174
  # Description: The directory which contains pom.xml file
  POM_XML_DIRECTORY: '.'
  # Description: The function app name in your local development.
  # TODO : Replace <pom_function_app_name> with the name of task. This can be found in your function's pom.xml, under the *'functionAppName'* tag under properties.
  POM_FUNCTIONAPP_NAME: my-first-function-20231027191045174
  # Description: The java version to use
  JAVA_VERSION: '1.8.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Java SDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Restore Project Dependencies Using Mvn
        shell: pwsh
        run: |
          pushd './${{ env.POM_XML_DIRECTORY }}'
          mvn clean package
          mvn azure-functions:package
          popd

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_STAGING_PUBLISH_PROFILE }}  # Replace with your staging publish profile secret
